### ISSUE TITLE
Merge leaves first char in output

### ISSUE THREAD

**Issue by rdev1983** [xahon/DiffMerge3#1]
I used equal text ("Ru") for base, left and right. when i run following code it output only 'u', it leaves 'R' in the output.

`int main()
{
    const char *base  = "Ru";
    const char *left  = "Ru";
    const char *right = "Ru";

    DiffMerge3::Merge3 merger(base, left, right);
    merger.Merge();

    for (size_t i = 0; i < merger.GetNumRegions(); i++)
    {
        const DiffMerge3::MergeRegion *section = merger.GetRegion(i);
        DiffMerge3::Merge3::PrintEntry(stdout, section);
    }

    fflush(stdout);

    return 0;
}`

**Comment by xahon** [comment]
Hello. Thanks for the report. Please check if https://github.com/xahon/DiffMerge3/tree/bugfix/issue-1 works for you
